version: '2'
services:
  php:
    container_name: docker-php
    image: php:7.0-fpm
    build: .
    volumes:
      - ..:/var/www/html/site
  nginx:
    container_name: docker-nginx
    image: nginx:latest
    volumes:
      - ..:/var/www/html/site
      - ./site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - 80:80
